[package]

name = "pcap"
version = "0.7.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "A packet capture API around pcap/wpcap"
keywords = ["pcap", "packet", "sniffing"]
readme = "README.md"
homepage = "https://github.com/ebfull/pcap"
repository = "https://github.com/ebfull/pcap"
documentation = "https://docs.rs/pcap"
license = "MIT OR Apache-2.0"
build = "build.rs"

[dependencies]
libc = "0.2"
clippy = { version = "0.0.*", optional = true }
mio = { version = "0.6", optional = true }
tokio-core = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
cc = "1.0"

[features]

# Build PCAP from source
build = []

# This feature enables access to the function Capture::savefile_append.
# This is disabled by default, because it depends on a relatively recent
# version of libpcap (1.7.2).
pcap-savefile-append = []

# This feature enables access to the function Capture::from_raw_fd_with_precision.
# This is disabled by default, because it requires libpcap >= 1.5.0.
pcap-fopen-offline-precision = []

# This feature enables access to the function Capture::stream.
# This is disabled by default, because it depends on a tokio and mio
tokio = ["mio", "tokio-core", "futures"]

# A shortcut to enable all features.
full = ["pcap-savefile-append", "pcap-fopen-offline-precision", "tokio"]

[lib]
name = "pcap"

[[example]]
name = "listenlocalhost"
path = "examples/listenlocalhost.rs"

[[example]]
name = "getdevices"
path = "examples/getdevices.rs"

[[example]]
name = "easylisten"
path = "examples/easylisten.rs"

[[example]]
name = "savefile"
path = "examples/savefile.rs"

[[example]]
name = "getstatistics"
path = "examples/getstatistics.rs"

[[example]]
name = "streamlisten"
path = "examples/streamlisten.rs"
